name: PPAAS
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.14
  - pip=24.2
  - python=3.9.19
  - readline=8.2
  - setuptools=72.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.9
      - aiosignal==1.3.1
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - black==24.10.0
      - botorch==0.10.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - decorator==5.1.1
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - farama-notifications==0.0.4
      - filelock==3.15.4
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - git-filter-repo==2.45.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gpytorch==1.11
      - grpcio==1.66.0
      - gymnasium==0.29.1
      - idna==3.8
      - imageio==2.35.1
      - importlib-metadata==8.4.0
      - importlib-resources==6.4.4
      - ipython==8.18.1
      - jaxtyping==0.2.34
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - linear-operator==0.5.1
      - lz4==4.3.3
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - numpy==2.0.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - opt-einsum==3.3.0
      - packaging==24.1
      - pandas==2.2.2
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.47
      - propcache==0.2.0
      - protobuf==5.27.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==17.0.0
      - pygments==2.18.0
      - pyparsing==3.1.4
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.2
      - ray==2.33.0
      - referencing==0.35.1
      - requests==2.32.3
      - rich==13.7.1
      - rpds-py==0.20.0
      - scienceplots==2.1.1
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - sentry-sdk==2.16.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - stable-baselines3==2.3.2
      - stack-data==0.6.3
      - sympy==1.13.2
      - tabulate==0.9.0
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.5.0
      - tifffile==2024.8.24
      - tomli==2.2.1
      - torch==2.4.0
      - torch-geometric==2.6.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - triton==3.0.0
      - typeguard==2.13.3
      - typer==0.12.5
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - wandb==0.18.3
      - wcwidth==0.2.13
      - werkzeug==3.0.4
      - yarl==1.14.0
      - zipp==3.20.0
